jms_translation:
    configs:
        symbb:
            dirs: 
                - %kernel.root_dir%/../vendor/symbb/symbb/SymBB/Core
                - %kernel.root_dir%/../vendor/symbb/symbb/SymBB/Template
            output_dir: %kernel.root_dir%/../vendor/symbb/symbb/SymBB/Template/DefaultBundle/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            external-translations-dir: 
                - %kernel.root_dir%/../vendor/symbb/symbb/SymBB/Extension/