services:
    symbb.extension.usertag.post.parse.text:
        class: SymBB\Extension\UserTagBundle\EventListener\ParseListener
        arguments: ['@symbb.core.user.manager']
        tags:
            - { name: kernel.event_listener, event: symbb.post.manager.parse.text, method: parsePostText, priority: -10 }

            
            
            
            