symbb_extension_calendar_get_events:
    pattern:  /calendar/events
    defaults: { _controller: SymbbExtensionCalendarBundle:Data:events}
    
symbb_extension_calendar_template:
    pattern:  /calendar/template/{template}.html
    defaults: { _controller: SymbbExtensionCalendarBundle:Data:template}
    
symbb_extension_calendar_template_dummy:
    pattern:  /calendar/template/
    defaults: { _controller: SymbbExtensionCalendarBundle:Data:template}
    
    