_symbb_acp:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Acp:list }
    
_symbbcoresitebundle_site_acp_routings:
    resource: "@SymBBCoreSiteBundle/Resources/config/routing/acp.yml"
    prefix: /
    
_symbbcoreforumbundle_forum_list:
    pattern:  /forum/list
    defaults: { _controller: SymBBCoreForumBundle:Acp:list }
    
_symbbcoreforumbundle_forum_list_child:
    pattern:  /forum/list/{parent}
    defaults: { _controller: SymBBCoreForumBundle:Acp:list }

_symbbcoreforumbundle_forum_new:
    pattern:  /forum/new/forum/{parent}
    defaults: { _controller: SymBBCoreForumBundle:Acp:new, parent: 0 }
    
_symbbcoreforumbundle_forum_new_category:
    pattern:  /forum/new/category/{parent}
    defaults: { _controller: SymBBCoreForumBundle:Acp:newCategory, parent: 0 }
    
_symbbcoreforumbundle_forum_new_link:
    pattern:  /forum/new/link/{parent}
    defaults: { _controller: SymBBCoreForumBundle:Acp:newLink, parent: 0 }

_symbbcoreforumbundle_forum_edit:
    pattern:  /forum/{id}/edit
    defaults: { _controller: SymBBCoreForumBundle:Acp:edit }
    
_symbbcoreforumbundle_forum_sort:
    pattern:  /forum/sort
    defaults: { _controller: SymBBCoreForumBundle:Acp:sort }
    
_symbbcoreforumbundle_forum_remove:
    pattern:  /forum/{id}/remove
    defaults: { _controller: SymBBCoreForumBundle:Acp:remove }
    
    
_symbbcoresystembundle_config:
    pattern:  /config
    defaults: { _controller: SymBBCoreSystemBundle:AcpConfig:index }
    
_symbbcoresystembundle_extensions:
    pattern:  /extensions
    defaults: { _controller: SymBBCoreSystemBundle:AcpExtension:index }
    
_symbbcoresystembundle_extension_disable:
    pattern:  /extension/{package}/disable
    defaults: { _controller: SymBBCoreSystemBundle:AcpExtension:disable }
    
_symbbcoresystembundle_extension_enable:
    pattern:  /extension/{package}/enable
    defaults: { _controller: SymBBCoreSystemBundle:AcpExtension:enable }
    
_symbbcoresystembundle_maintenance:
    pattern:  /maintenance
    defaults: { _controller: SymBBCoreSystemBundle:AcpMaintenance:index }
    
    
    
_symbbcorebbcodebundle_bbcode_list:
    pattern:  /bbcode/list
    defaults: { _controller: SymBBCoreBBCodeBundle:Acp:list }

_symbbcorebbcodebundle_bbcode_new:
    pattern:  /bbcode/new
    defaults: { _controller: SymBBCoreBBCodeBundle:Acp:new}
    
_symbbcorebbcodebundle_bbcode_edit:
    pattern:  /bbcode/{id}/edit
    defaults: { _controller: SymBBCoreBBCodeBundle:Acp:edit }
    
_symbbcorebbcodebundle_bbcode_remove:
    pattern:  /bbcode/{id}/remove
    defaults: { _controller: SymBBCoreBBCodeBundle:Acp:remove }
    
_symbbcorebbcodebundle_bbcode_sort:
    pattern:  /bbcode/sort
    defaults: { _controller: SymBBCoreBBCodeBundle:Acp:sort }
    
_symbbcorebbcodebundle_bbcode_restore:
    pattern:  /bbcode/restore
    defaults: { _controller: SymBBCoreBBCodeBundle:Acp:restore }
    
    
_symbb_core_user_acp:
    resource: "@SymBBCoreUserBundle/Resources/config/routing/acp.yml"
    prefix: /