symbb_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }
    
symbb_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    
symbb_login_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    
fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    
symbb_register:
    pattern:  /register
    defaults: { _controller: SymBBFOSUserBundle:Registration:register }
    
symbb_imprint:
    pattern:  /imprint
    defaults: { _controller: SymBBCoreSystemBundle:StaticPage:imprint }
    
symbb_terms:
    pattern:  /terms
    defaults: { _controller: SymBBCoreSystemBundle:StaticPage:terms }
    
_symbbcoresitebundle_site_frontend_routings:
    resource: "@SymBBCoreSiteBundle/Resources/config/routing/frontend.yml"
    prefix: /

_symbb_core_user:
    resource: "@SymBBCoreUserBundle/Resources/config/routing.yml"
    prefix: /ucp
    
_symbb_core_forum:
    resource: "@SymBBCoreForumBundle/Resources/config/routing.yml"
    prefix: /
    
_symbb_core_install:
    resource: "@SymBBCoreInstallBundle/Resources/config/routing.yml"
    prefix: /